### ISSUE TITLE
MCI Survival release progress 1.17

### ISSUE THREAD

**Issue by smyaknti** [MCIndiaNetwork/MCI-Server#1]
We shall keep updating this thing from time to time as our progress goes ahead! Stay tuned! Most recent updates will be posted as comments after this issue!

### Our todo list:
- [x] Setting up staff only test server to build up spawn
- [x] Spawn Build Finalisation
   - [x] World Setup
   - [x] Base build
   - [x] Major Places of attraction
   - [x] Market
   - [x] Boost pads
   - [x] Special places
- [x] Load in and test the old world with Boss Arena (Yes Boss Arena is planned from day 1)
   - [x] Base world and spawn loaded
   - [x] Additional worlds to test
- [x] Do agressive testing to check for gamebreaking bugs which might require a world reset
- [x] Open server up in beta (Progress can reset any day untill things are stable)
   - [x] Admins only as main world is live!
   Note: Staff members who would play survival would not be allowed yet!
- [x] Wait for all major plugins to support `Java 16` and `Minecraft v1.17` 
- [x] Finish up the battle-pass progression system
- [x] Release MCI Survival Season 3 with the Caves and Cliffs update Part 1
    - Release is still BETA as no plugins are stable yet.
    - Daily backups would be taken and progress can reset anytime.

### Important note:

This issue is to share our progress report with our public community so that people are not asking in game chat about survival. Yes we are working on it. 😄 

### Some important points about how survival will operate:
- The world will be limited for the part 1 update so that we can trim the rest of the world for part 2 to come with the new terrain generation. You people won't have to go searching for the chunks then! 😛 
- The progression system will include a battle pass with free and paid tiers. More info on it will be explained later.
- We do not want to release with a broken gameplay experience so we would fix things before we release.
- Staff wont have any advantage as the test server is limited to spawn and the rest of the world will be trimmed before release anyway! 👌🏻

**Comment by smyaknti** [comment]
**Major Change**: Authentication and Permission Plugins are up.
**Minor Change**: Skins and World Edit works in a hacky way

Status: Spawn is being built.

**Comment by smyaknti** [comment]
Majority of the Spawn has been built. Spawn is way bigger and shall come with possible quests! 😉

**Comment by smyaknti** [comment]
Spawn build is done 😄 
Most plugins have updated.
Two major ones are left: Land Claims and Custom Mobs 😢

**Comment by smyaknti** [comment]
PaperMC is now (apparently) stable!
Yesterday we tested a mini UHC game. It was okay ish. Survival runs fine for now with less people. We shall keep testing.

Hardware upgrades are due as well. 
If we launch initially we may keep it in test phases for a few days and reset as needed! :D

**Comment by smyaknti** [comment]
Major changes: Hardware has been upgraded for season 3!
Server restarts in under 30 Seconds! 👌🏻 

Almost all plugins seem to work.
Custom Mobs are still not here so XPfarm might be delayed.

**Comment by SpikeyHelmet** [comment]
Major fixes and glitches have been fixed out. Security has been improved.
Just testing for a few days. ETA for release would be announced tomorrow.

**Comment by SpikeyHelmet** [comment]
Quick note: Just like Mojang 🐱‍🏍 we have planned to release the update in two phases

💠 The first phase  would include most of the planned features which would be a fully functioning economy with shops and admin shops

💠 The second phase would come a later and largely depends on the plugin support.
this phase would include the XPFarms, Bosses and Battlepass progression systems.

PS: Only 1.17 clients will be allowed to play on Survival. We will not be supporting older versions as there are a lot of features & gameplay experiences that will not work on these older clients.

Bedrock editions will be supported from Day 1 regardless.

**Comment by SpikeyHelmet** [comment]
Phase 1 Begins on 2nd July 10AM.

**Comment by SpikeyHelmet** [comment]
======= Phase 2 Report =========

- MythicMobs now supports 1.17 but it is still very unstable, due to this XPFarm will be delayed until the plugin is fixed.
- Crates & Battlepass are being worked on.

Finally coming to say that the server is now **"STABLE"**. Until Phase 2 rolls out we would still consider it as a **BETA**.

ETA for a full Phase 2 rollout would be by the end of August.

**Comment by SpikeyHelmet** [comment]
===== Phase 2 Update =======

* Crates are now Live, Battlepass to be added by the end of this week

We still have no info on MythicMobs

**Comment by SpikeyHelmet** [comment]
Pre-final update to survival 1.17

* XPFarm has been added back
* Crates are Live
* Battlepass progression system has been deployed.

The final update will consist of Bosses and QOL updates
