### ISSUE TITLE
[BUG] Rank and codes not showing

### ISSUE THREAD

**Issue by NonOfficial352** [MCIndiaNetwork/MCI-Server#12]
### ✅ Checklist

- [X] Survival
- [ ] Oneblock
- [ ] Skyblock
- [ ] Minigames

### 📋 Description

when you disconnect and login in the server, in the tab screen ur codes are not shown rather the real username is. but once you type something in chat, codes come back. and also scoreboard is not showing that you have friendly or which rank
![2021-12-06_06 51 40](https://user-images.githubusercontent.com/85988121/144834398-93bdf1d8-2435-4cb5-9a67-bf5c12a93349.png)

### 💡 Expected Behavior

to show codes in tab screen without tying anything in chat. and to see the specific donator rank i have

### 🎮 Minecraft Version

1.16.x

### 🎮 Minecraft Client Mod

Optifine

### 🎮 Operating system 

Linux

**Comment by Gamer027421** [comment]
As of your first bug it doesn't seem like a big issue but we will surely take care of the 2nd Part

**Comment by SpikeyHelmet** [comment]
Issue has been fixed, along with the oneblock ingame rank bug
