### ISSUE TITLE
[BUG] TnT Run Block Gltich

### ISSUE THREAD

**Issue by Kingster3742** [MCIndiaNetwork/MCI-Server#13]
### ✅ Checklist

- [ ] Survival
- [ ] Oneblock
- [ ] Skyblock
- [X] Minigames

### 📋 Description

![image](https://user-images.githubusercontent.com/86717948/145003414-b741d361-c64d-494c-bece-8fb74937199a.png)
Look at the image, Prospidy was stuck there and won that round. Each player can do that cause 3 peeps were doing this that round. (more images attached below.

### 📑 Reproduction Steps (Optional)

Am not sure honestly how to do it ;-; (Ask Prospidy)

### 💡 Expected Behavior

Fall because of Gravity

### 📷 Screenshots / Videos

![image](https://user-images.githubusercontent.com/86717948/145003605-5db2b8cf-87fb-4f73-ba00-ff2188c244b2.png)
![image](https://user-images.githubusercontent.com/86717948/145003725-aab7eeaf-481c-45f8-9681-b9d9d85c84f8.png)

### 🎮 Minecraft Version

1.8.9

### 🎮 Minecraft Client Mod

Vanilla

### 🎮 Operating system 

Windows

**Comment by shramann** [comment]
well u have to crouch and get on the stairs
its not quite a glitch but a game breaking opening in the map

**Comment by Kingster3742** [comment]
> 

Ye so fix the map and remove the stairs from there :pepeshrug:

**Comment by Prospidy** [comment]
well map needs to be changed

**Comment by Kingster3742** [comment]
> well map needs to be changed

ye

**Comment by SpikeyHelmet** [comment]
Fixed!
