### ISSUE TITLE
[BUG] Hunger goes Down In Mg Lobby Area

### ISSUE THREAD

**Issue by Kingster3742** [MCIndiaNetwork/MCI-Server#14]
### ✅ Checklist

- [ ] Survival
- [ ] Oneblock
- [ ] Skyblock
- [X] Minigames

### 📋 Description

Hunger goes down in mg, can't sprint after sometime cause of it

### 📑 Reproduction Steps (Optional)

Uhhh Keep running then hunger will go down

### 💡 Expected Behavior

Did not expect it to go down but stay full

### 📷 Screenshots / Videos

![image](https://user-images.githubusercontent.com/86717948/145005098-c5d904d1-71e6-410b-95bb-2796903b472a.png)

### 🎮 Minecraft Version

1.8.9

### 🎮 Minecraft Client Mod

Vanilla

### 🎮 Operating system 

Windows

**Comment by shramann** [comment]
well yea

**Comment by SpikeyHelmet** [comment]
Fixed!
