### ISSUE TITLE
[BUG] Buggy pvp in pvp arena OB

### ISSUE THREAD

**Issue by shramann** [MCIndiaNetwork/MCI-Server#15]
### ✅ Server

- [ ] Survival
- [X] Oneblock
- [ ] Skyblock
- [ ] Minigames

### 📋 Description

OB pvp in pvp arena is still buggy af 
Spikey told in changelog that pvp was fixed ,the thorns prob got fixed,now  its a kb and dmg amplification problem.
It happens most of the times and is more annoying than the thorns prob

Once we hit a player,they lose 3hears and automatically gets kb and loses another 3hearts(by automatically gets kb i mean that tho we didnt gave the player kb but still he gets 2shots dmg in 1shot 
and thus,we die in 2shots

### 📑 Reproduction Steps (Optional)

Fix the kb problem and damage amplification problem.

### 💡 Expected Behavior

Pvp should work smoothly or if 1.8 pvp is making much probs then make it 1.16 pvp best

### 🎮 Minecraft Version

1.17.x

### 🎮 Minecraft Client Mod

Optifine

### 🎮 Operating system 

Windows

### 💡 Extra Client Mods (Optional)

None

@elli0t43

**Comment by SpikeyHelmet** [comment]
Will look into this tonight, it's possibly a 1.8 KB Issue

**Comment by SpikeyHelmet** [comment]
Issue has been fixed!
