### ISSUE TITLE
[BUG]Auction house doesnt let to change the amount of starting bid

### ISSUE THREAD

**Issue by Adityakhalkar** [MCIndiaNetwork/MCI-Server#16]
### ✅ Server

- [ ] Survival
- [X] Oneblock
- [ ] Skyblock
- [ ] Minigames

### 📋 Description

when we want to change the starting bid of any item in auction house, it is not showing anything on clicking the gold_ingot
while the gold_ingot has the lore written "click to edit"

### 📑 Reproduction Steps (Optional)

1.type /ah
2.click Manage auctions(golden_horse_armour)
3.click any item from your inventory that you want to sell in ah 
4.click on the gold_ingot to change the starting bid
5. nothing happens

### 💡 Expected Behavior

 A new GUI was to open 
 or
 a message saying type the starting bid should be displayed in the chat, and we give the starting bid amount in it

### 📷 Screenshots / Videos

![Screenshot (460)](https://user-images.githubusercontent.com/67951994/145414493-7b965564-aced-43ee-81da-cb9ebaf6a1a6.png)

### 🎮 Minecraft Version

1.17.x

### 🎮 Minecraft Client Mod

Fabric

### 🎮 Operating system 

Windows

### 💡 Extra Client Mods (Optional)

nope

**Comment by SpikeyHelmet** [comment]
Issue has been fixed
