### ISSUE TITLE
[BUG] Not getting some items after claiming in the reward in Oneblock challenges 

### ISSUE THREAD

**Issue by Adityakhalkar** [MCIndiaNetwork/MCI-Server#17]
### ✅ Server

- [ ] Survival
- [X] Oneblock
- [ ] Skyblock
- [ ] Minigames

### 📋 Description

After we claim the awards that we get from ob challenges, some of the awards are not getting in the inventory/dropping on ground, even if the inventory is not full. like the shulker boxes from the nether star challenge in the advanced Oneblock challenge

### 📑 Reproduction Steps (Optional)

there are 3-4 of the ob challenges that perform this bug, but i am going to tell the one i wrote in description
1.Reach the advanced ob challenges
2.Get one nether star.
3.click on the nether star challenge
4.it will give a congratulations message, but you wont get the shulker boxes as written in the lore
5.you will just get the 4 diamond blocks

### 💡 Expected Behavior

The Shulker boxes must come in inventory of player, if the inventory of player is full, it must drop on the ground or go to the player ec if any space there

### 🎮 Minecraft Version

1.17.x

### 🎮 Minecraft Client Mod

Optifine

### 🎮 Operating system 

Windows

### 💡 Extra Client Mods (Optional)

nope

**Comment by SpikeyHelmet** [comment]
Resolved
