### ISSUE TITLE
[BUG]Some Barrier blocks are missing at high y-levels in Oneblock Xpfarm

### ISSUE THREAD

**Issue by Adityakhalkar** [MCIndiaNetwork/MCI-Server#18]
### ✅ Server

- [ ] Survival
- [X] Oneblock
- [ ] Skyblock
- [ ] Minigames

### 📋 Description

Players can get inside the Oneblock xpfarms , with the use of enderpearls and some holes in the barrier blocks protection, so basically these holes are at 2 places till what i have seen,
1) At the top front of the castle.
2) the other side of the first xpfarm (the door)

### 📑 Reproduction Steps (Optional)

1) get to the places as mentioned above
2) get a enderpearl, through it through the holes
3) poof!!! you are in

### 💡 Expected Behavior

The Barrier blocks must be evenly placed everywhere and spoilers to the xpfarms must be prevented, also i know that Xpfarms are going to come very soon 

> but as said can be SST
So fix the bug

### 📷 Screenshots / Videos

i know you want the screenshots i will provide them in some time below

### 🎮 Minecraft Version

1.17.x

### 🎮 Minecraft Client Mod

Optifine

### 🎮 Operating system 

Windows

### 💡 Extra Client Mods (Optional)

nope

**Comment by SpikeyHelmet** [comment]
Revamping oneblock!
