### ISSUE TITLE
[BUG] There are two MCMMO bugs in Oneblock

### ISSUE THREAD

**Issue by Adityakhalkar** [MCIndiaNetwork/MCI-Server#19]
### ✅ Server

- [ ] Survival
- [X] Oneblock
- [ ] Skyblock
- [ ] Minigames

### 📋 Description

1)When we type /mining and click any of the sub skills, it shows that this subskill doesnt exist, but in reality we can use it 
2)we cant do the /repair command, i think its bugged with the donor rank one command, while its used to get information about our repair lvl up

### 📑 Reproduction Steps (Optional)

for 1st bug
1. type /mining 
2. click any of the subskills after unlocking
3. it will show the subskill doesn't exist!!

for 2nd bug
 1.type /repair
 2.it shows you dont have permission for this command( Exalted people have permission, so they will just repair there armour  
 instead)

### 💡 Expected Behavior

for 1st bug, it should describe more about the subskill

for 2nd bug, it should show the MCMMO repair lvlup  information

### 🎮 Minecraft Version

1.17.x

### 🎮 Minecraft Client Mod

Optifine

### 🎮 Operating system 

Windows

### 💡 Extra Client Mods (Optional)

nope

**Comment by SpikeyHelmet** [comment]
Will wait for a fix from mcmmo.

**Comment by Adityakhalkar** [comment]
this issue has been fixed as reported by @Undercover07
