### ISSUE TITLE
Hey here is they way u play MCI on mobile

### ISSUE THREAD

**Issue by Saffronpvp** [MCIndiaNetwork/MCI-Server#2]
HELLO spikey or Sammmy

Here's the way mcpe player can join MCI
BUT THEY GONNA JOIN USING NEW APP
IT CALLED POJAV LANCHER IT TOTALLY SAFE
IT CAN BE PLAY MC JAVA ON MOBILE WITH USING ANY MOD LIKE OPTIFINE,FORGE,FABRIC,ETC...
IF U LIKE THIS IDEA
PLZ SHARE ON DISCORD SO EVERYONE CAN USE THIS .
👇👇👇👇👇👇
HERE IS THE STEPS:
OPEN PLAY STORE.SEARCH:POJAV LANCHER
![IMG_20210627_132847](https://user-images.githubusercontent.com/86413485/123537271-31ec7b00-d74c-11eb-9285-bd19b7fbe1bf.jpg)
#
Then open
![IMG_20210613_182449](https://user-images.githubusercontent.com/86413485/123537305-606a5600-d74c-11eb-9443-c66fa54c1ecf.jpg)
If U HAVE LEGIT ACCOUNT U CAN ENTER .IF U NOT HAVE JUST ENTER WHAT USERNAME ON WHERE I MARKED
![IMG_20210627_133646](https://user-images.githubusercontent.com/86413485/123537431-0cac3c80-d74d-11eb-87c3-10942435e6b9.jpg)
FILLED ONE LOOK LIKE THIS
![IMG_20210627_133755](https://user-images.githubusercontent.com/86413485/123537443-1d5cb280-d74d-11eb-95ea-fef8a0c188a1.jpg)
AND LOGIN
![IMG_20210627_134030](https://user-images.githubusercontent.com/86413485/123537483-4bda8d80-d74d-11eb-8dfa-04416ae8f3ab.jpg)
And DOWNLOAD WHAT VERSION U WANT AND DOWNLOAD 
__________
NEXT OPEN OPTIONS NEXT 
![IMG_20210613_182808](https://user-images.githubusercontent.com/86413485/123537530-83493a00-d74d-11eb-99fe-07434265cc47.jpg)
![IMG_20210613_182849](https://user-images.githubusercontent.com/86413485/123537532-85ab9400-d74d-11eb-8c04-749c7d0d525a.jpg)
  SET HOW MUCH RAM U WANT GIVE 
AND PLAY 
![Screenshot_2021-06-09-18-17-29-106_net kdt pojavlaunch](https://user-images.githubusercontent.com/86413485/123537568-b8558c80-d74d-11eb-84d3-770f0627b76e.jpg)
![Screenshot_2021-06-10-17-44-52-868_net kdt pojavlaunch](https://user-images.githubusercontent.com/86413485/123537570-bab7e680-d74d-11eb-9888-b9678a49e4e2.jpg)
NOTE IF U HAVE LEGIT ACCOUNT U CAN PLAY
U CAN PLAY HYPIXEL:
![Screenshot_2021-06-24-17-41-30-708_net kdt pojavlaunch](https://user-images.githubusercontent.com/86413485/123537585-cefbe380-d74d-11eb-8e88-621f3af48e20.jpg)

![Screenshot_2021-06-23-08-48-10-722_net kdt pojavlaunch](https://user-images.githubusercontent.com/86413485/123537577-c7d4d580-d74d-11eb-8988-7a736b635126.jpg)

**Comment by Saffronpvp** [comment]
Plz SAMMY

**Comment by Saffronpvp** [comment]
Write any comments

**Comment by smyaknti** [comment]
We understand that this is a way to play minecraft on phone but this is java minecraft emulated on android where there is already an pre intended game by mojang which is specific for android. 
As always, we do not openly condone any launcher/application on MCI.
As for bedrock players, we have set up ways for them to join via the official MCPE App by mojang. (There are multiple reasons as to why MCPE is different from java)

Its not advised to promote certain applications on a public discord which does not openly support any non standard protocols. Yes you can tell your friends about it but I suggest not openly on the server. :)
