### ISSUE TITLE
[BUG] ingot factory bugged as singularity maker

### ISSUE THREAD

**Issue by NonOfficial352** [MCIndiaNetwork/MCI-Server#20]
### ✅ Server

- [X] Survival
- [ ] Oneblock
- [ ] Skyblock
- [ ] Minigames

### 📋 Description

i dont know if this is a bug or what. but an ingot factory-III got bugged as singu. maker, if u right click it. it shows gui of ingot factory but the green glass pane is of singu. maker. when you break the block it drops a singu. maker and blue and orange glass pane(the illegal ones). this happened 3 times to me(2 time at same block  and 1 time at different block.

https://user-images.githubusercontent.com/85988121/145667317-1cbbca5e-b959-43d2-bb8f-b5fa44b5d4a8.mp4

### 💡 Expected Behavior

-

### 🎮 Minecraft Version

1.16.x

### 🎮 Minecraft Client Mod

Optifine

### 🎮 Operating system 

Linux

**Comment by SpikeyHelmet** [comment]
it's quite possible it might have been fixed with the new SF update.

kindly recheck and let us know.

**Comment by NonOfficial352** [comment]
i think maybe its because the block didnt reset what it had before, like it may hav had data that there is ingot factory still here(if this exist)
