### ISSUE TITLE
[BUG] Oneblock visit is bugged

### ISSUE THREAD

**Issue by Adityakhalkar** [MCIndiaNetwork/MCI-Server#21]
### ✅ Server

- [ ] Survival
- [X] Oneblock
- [ ] Skyblock
- [ ] Minigames

### 📋 Description

when we try to visit a Oneblock base, and the owner had set a amount to visit it, a message is shown that you need to pay 'X' amount to visit and type the same command to confirm, when we do so, it takes our money but doesnt teleport us there.

### 📑 Reproduction Steps (Optional)

1.write /ob visit {playername} (here playername needs to be the ones those have a specific amount set to visit)
2.it will tell you type same command again
3.have the amount of money thats needed
3.you type the same command again
4.it will take your money and not teleport you to the island

### 💡 Expected Behavior

the player must be teleported to the island after taking the price

### 📷 Screenshots / Videos

![Screenshot (462)](https://user-images.githubusercontent.com/67951994/145704954-b02802f8-11fd-45fd-bf21-0c50f2103e23.png)

### 🎮 Minecraft Version

1.17.x

### 🎮 Minecraft Client Mod

Optifine

### 🎮 Operating system 

Windows

### 💡 Extra Client Mods (Optional)

none

**Comment by SpikeyHelmet** [comment]
Thanks for letting me know about the specifics this issue should be solved by Tuesday

**Comment by Adityakhalkar** [comment]
> Thanks for letting me know about the specifics this issue should be solved by Tuesday

i guess the issue is solved, you can close the issue if you want
