### ISSUE TITLE
[BUG] Magic Sugar from friendly kit doesnt work

### ISSUE THREAD

**Issue by Adityakhalkar** [MCIndiaNetwork/MCI-Server#22]
### ✅ Server

- [X] Survival
- [ ] Oneblock
- [ ] Skyblock
- [ ] Minigames

### 📋 Description

When we cl[aim the frientdly kit, we get some things like armors , tools, keys and a magic sugar, this magic sugar when right clicked doesnt do anything

### 📑 Reproduction Steps (Optional)

1.Donate to the server for friendly rank
2.Claim the friendly kit
3.right click the magic sugar from the kit
4.nothing happens

### 💡 Expected Behavior

On right clicking the Magic sugar, we must get a Speed buff

### 🎮 Minecraft Version

1.17.x

### 🎮 Minecraft Client Mod

Optifine

### 🎮 Operating system 

Windows

### 💡 Extra Client Mods (Optional)

nope

**Comment by SpikeyHelmet** [comment]
Issue has been fixed for all donator kits.
