### ISSUE TITLE
[BUG] In Oneblock Slow falling potion is bugged, we cant make it

### ISSUE THREAD

**Issue by Adityakhalkar** [MCIndiaNetwork/MCI-Server#23]
### ✅ Server

- [ ] Survival
- [X] Oneblock
- [ ] Skyblock
- [ ] Minigames

### 📋 Description

when we try to make the slow falling potion, it completes the arrow animation in the brewing stand, but doesn't make the potion
also thanks to Boy_droid, we can make slow falling splash potion but not the actual potion( so idts, its 1.8 mechanism problem as slow falling splash potion was added in 1.13)
(PS:- idk if its a bug or not, but i guess configure the alchemy mechanism if you can for mcmmo, as the OB follows 1.8 mechanism while slow falling potion was added in 1.13)

### 📑 Reproduction Steps (Optional)

1.get all the ingredients for the slow falling potion( brewing stand, nether wart, blaze powder, water bottle and a phantom membrane)
2.put the blaze powder in fuel section and nether wart in the main slot and a water bottle in the bottle slots
3.when awkward potion is made, put a phantom membrane in the main slot
4.it will do the animation but never make the slow falling potion

### 💡 Expected Behavior

The Slow falling potion must be made by the brewing stand

### 📷 Screenshots / Videos

![image](https://user-images.githubusercontent.com/67951994/145709429-8a697526-2a89-4064-94de-ec5d45179b1b.png)

### 🎮 Minecraft Version

1.17.x

### 🎮 Minecraft Client Mod

Optifine

### 🎮 Operating system 

Windows

### 💡 Extra Client Mods (Optional)

nope

**Comment by SpikeyHelmet** [comment]
You can't make potions from due to them being craftable by a different method with McMMO.
