### ISSUE TITLE
[BUG] Oneblock Voting Menu needs a revamp

### ISSUE THREAD

**Issue by Adityakhalkar** [MCIndiaNetwork/MCI-Server#25]
### ✅ Server

- [ ] Survival
- [X] Oneblock
- [ ] Skyblock
- [ ] Minigames

### 📋 Description

The Voting Menu in Oneblock is same as the one in Survival, showing things like 30 claim blocks.

### 📑 Reproduction Steps (Optional)

1. Type /vote in Oneblock
2. You will get a GUI with written 30 claim blocks

### 💡 Expected Behavior

 I guess it must be changed and instead of 30 claim blocks, OB level of the respective player must increase by 3-5 levels.

### 📷 Screenshots / Videos

I will try to edit for this one

### 🎮 Minecraft Version

1.17.x

### 🎮 Minecraft Client Mod

Fabric

### 🎮 Operating system 

Windows

### 💡 Extra Client Mods (Optional)

Nope

**Comment by SpikeyHelmet** [comment]
Fixed.
