### ISSUE TITLE
[BUG] Players can get in the jail 

### ISSUE THREAD

**Issue by Adityakhalkar** [MCIndiaNetwork/MCI-Server#26]
### ✅ Server

- [X] Survival
- [ ] Oneblock
- [ ] Skyblock
- [ ] Minigames

### 📋 Description

Players can get inside the jails by eating a chorus fruit, but those who are jailed but dont have chorus fruits cant get out
also for small jails, the normal pearl can be glitched into the stairs or half blocks like slabs which have airpockets

### 📑 Reproduction Steps (Optional)

1. get a chorus fruit
2. go to the MadMallu jail for the best experience as it is very big
3. eat the chorus fruit few times 
4. poof u are in jail with the Master MadMallu
5. or get like a stack of ender pearls
6. spam throw the pearls at the stairs and poof u got a new base

### 💡 Expected Behavior

The players should get a message like you cant eat this item here 
                                    OR
                You cant Teleport after eating it 

### 📷 Screenshots / Videos

![Screenshot (464)](https://user-images.githubusercontent.com/67951994/146188800-35d51b5f-c9c7-4fa9-89a5-c7aca8a51e52.png)

![Screenshot (465)](https://user-images.githubusercontent.com/67951994/146190195-fdf95c79-2d4a-41a3-8755-c91876c58f6f.png)

### 🎮 Minecraft Version

1.17.x

### 🎮 Minecraft Client Mod

Optifine

### 🎮 Operating system 

Windows

### 💡 Extra Client Mods (Optional)

nope

**Comment by SpikeyHelmet** [comment]
It's the curse of MadMallu
sadly you have to die to get rid of it 🙁

**Comment by Gamer027421** [comment]
> It's the curse of MadMallu sadly you have to die to get rid of it 🙁
> 
> Jokes aside I'll look into it

A fix is not really needed this issue has been there since season 1

**Comment by Adityakhalkar** [comment]
> > It's the curse of MadMallu sadly you have to die to get rid of it 🙁
> > Jokes aside I'll look into it
> 
> A fix is not really needed this issue has been there since season 1

How can you say its a issue and a fix is not needed in same sentence? if its a issue, fix is the only thing it needs

**Comment by SpikeyHelmet** [comment]
Well this does not need a fix. just don't go to visit your friends in jail :)
