### ISSUE TITLE
Visits Bugged in Oneblock

### ISSUE THREAD

**Issue by DestinedPhoenix** [MCIndiaNetwork/MCI-Server#27]
### ✅ Server

- [ ] Survival
- [X] Oneblock
- [ ] Skyblock
- [ ] Minigames

### 📋 Description

POV of the island owner: No island locked, all including visitors allowed.
My POV: BentoBox (the plugin) shows that visits are disabled in this island.
We also tried trusting myself to that island but still can't visit it. 

### 📑 Reproduction Steps (Optional)

/ob visit WARRIORESS
Display: Visits are disabled on this island.

### 💡 Expected Behavior

To be teleported to that island.

(Another thing is the message is different, we should get this island is locked message, but that doesn't come, instead a message appears visits are disabled on this island. (SO THIS MIGHT BE A MISUNDERSTANDING ON OUR SIDE).

### 🎮 Minecraft Version

1.18

### 🎮 Minecraft Client Mod

Optifine

### 🎮 Operating system 

Windows

### 💡 Extra Client Mods (Optional)

None

**Comment by DestinedPhoenix** [comment]
I'll add screenshots in some time.

**Comment by Adityakhalkar** [comment]
Duplicate of #21

**Comment by DestinedPhoenix** [comment]
No not exactly the same.
Issue #21 is about payment this is about OB Lock...

**Comment by Adityakhalkar** [comment]
> No not exactly the same. Issue #21 is about payment this is about OB Lock...

actually #21 was also happening due to ob was locked, there is a setting that we can lock the ob and people can only visit using money. but your issue is regarding ob is locked and that too only on the visitor side,this could be solved by rechecking the ob settings by /ob visit configure

**Comment by Adityakhalkar** [comment]
![Screenshot (466)](https://user-images.githubusercontent.com/67951994/146637058-a574c25e-8b47-4be0-bbf3-a2279344c83d.png)
just toggle this and done, your issue is solved

**Comment by DestinedPhoenix** [comment]
Yes done, thanks...
