### ISSUE TITLE
[BUG] In the warps menu XPfarm warp still says coming soon

### ISSUE THREAD

**Issue by TheGlitch2731** [MCIndiaNetwork/MCI-Server#28]
### ✅ Server

- [X] Survival
- [ ] Oneblock
- [ ] Skyblock
- [ ] Minigames

### 📋 Description

In the warps menu XPfarm warp still says coming soon even though xp farm is functional. This causes confusion for new players who may open the warp menu

### 📑 Reproduction Steps (Optional)

1. do /warps 

### 💡 Expected Behavior

In the warps menu XPFarm shouldnt have coming soon tag

### 📷 Screenshots / Videos

![2021-12-23_09-04](https://user-images.githubusercontent.com/79125737/147184982-60bb7cad-f412-416e-9ac4-0b923b6cd021.png)

### 🎮 Minecraft Version

1.17.x

### 🎮 Minecraft Client Mod

Fabric

### 🎮 Operating system 

Linux

### 💡 Extra Client Mods (Optional)

![2021-12-23_09-16](https://user-images.githubusercontent.com/79125737/147185060-4fbf73b1-e9e9-4ccb-9f25-83cdd0fe1f92.png)
![2021-12-23_09-16_1](https://user-images.githubusercontent.com/79125737/147185067-bc205a2f-fcec-4bd6-b278-6d1a6d87bc85.png)

**Comment by SpikeyHelmet** [comment]
Issue has been resolved.
