### ISSUE TITLE
[BUG] The SkyWars Stats Getting Reset

### ISSUE THREAD

**Issue by hyprex-deva** [MCIndiaNetwork/MCI-Server#29]
### ✅ Server

- [ ] Survival
- [ ] Oneblock
- [ ] Skyblock
- [X] Minigames

### 📋 Description

The Skywars Stats which I had (Level 1, Wins 2, Kills 5), all got reset.
And Now it only Shows only Zero. (Level 0, Wins 0, Kills 0)

### 💡 Expected Behavior

It was expected to show the show the same stats and update it further when we play more matches.

### 📷 Screenshots / Videos

<img width="257" alt="Screenshot 2021-12-23 181133" src="https://user-images.githubusercontent.com/96543076/147241967-bf1725b8-1f3c-4503-b488-525ea9074372.png">

### 🎮 Minecraft Version

1.17.x

### 🎮 Minecraft Client Mod

Optifine

### 🎮 Operating system 

Windows

**Comment by SpikeyHelmet** [comment]
Issue has been noted. Sadly this was an issue that was reported on day one. It seems to be an issue with the plugin whenever someone gets kicked out.

I've reset everyone's stats and used an alternate method of saving data, hopefully this should solve the issue, the change has been made, close this ticket after a week if the issue has been resolved.
