### ISSUE TITLE
[BUG] Scoreboard got Removed after yesterday nights maintenance

### ISSUE THREAD

**Issue by DestinedPhoenix** [MCIndiaNetwork/MCI-Server#30]
### ✅ Server

- [ ] Survival
- [X] Oneblock
- [ ] Skyblock
- [ ] Minigames

### 📋 Description

The scoreboard that showed the phase your name and your votes is not there now.
We also dont have permission to do /sb toggle.
This is a minor bug, but i am just reporting such that its brought to light and can be fixed easily too.

### 📑 Reproduction Steps (Optional)

login and join oneblock
find the scoreboard missing
do /sb toggle to try to check it
find that you dont have permission to do that

### 💡 Expected Behavior

To see the scoreboard on the right hand side
TO have the scoreboard back when you do /sb toggle

### 📷 Screenshots / Videos

![2021-12-25_12 06 35](https://user-images.githubusercontent.com/96323384/147379079-5fd9811b-4501-43fd-96e7-8a2b62505a50.png)
![2021-12-25_12 06 42](https://user-images.githubusercontent.com/96323384/147379080-e0a0e6fd-4a40-46ee-914a-95e0a79a0238.png)

### 🎮 Minecraft Version

1.18

### 🎮 Minecraft Client Mod

Optifine

### 🎮 Operating system 

Windows

### 💡 Extra Client Mods (Optional)

none

**Comment by elli0t43** [comment]
did you tried the command `/sb toggle` ?

**Comment by elli0t43** [comment]
it might be disabled from your side, thats why its hidden

**Comment by RohanKohalli** [comment]
![Screenshot (38)](https://user-images.githubusercontent.com/66159081/147386679-a564e1aa-08d4-413d-b3ec-f3ad69ca6a21.png)
we don't have access to command /sb toggle

**Comment by DestinedPhoenix** [comment]
> ![Screenshot (38)](https://user-images.githubusercontent.com/66159081/147386679-a564e1aa-08d4-413d-b3ec-f3ad69ca6a21.png) we don't have access to command /sb toggle

Exactly... Check second screenshot i have attached.

**Comment by DestinedPhoenix** [comment]
> it might be disabled from your side, thats why its hidden

Moreover, everyone is facing this problem check discord community help.

**Comment by elli0t43** [comment]
Yes, I asked others, wait for spikey, he will fix it after sometime.

**Comment by DestinedPhoenix** [comment]
Ok. It's not a major bug, just we need the perms and it will maybe work.

**Comment by DestinedPhoenix** [comment]
Still this bug is not fixed. When you join you might get scoreboard most of the times, and later if you do /survival, play something else and comeback it is disappeared. Moreover, still no perms for /sb toggle.

**Comment by SpikeyHelmet** [comment]
Yesh, i've fixed this bug today.. Let me know if it occurs, this happened due to the new update of the plugin.. Issue is sorted now

**Comment by DestinedPhoenix** [comment]
@SpikeyHelmet it does happen still. The difference is when you join OB once you login SB is visible. After doing /survival, and then coming back after sometime the SB disappears. If you want a video, i can send it tomorrow.
