### ISSUE TITLE
[BUG] %Key% for /sit

### ISSUE THREAD

**Issue by DestinedPhoenix** [MCIndiaNetwork/MCI-Server#31]
### ✅ Server

- [X] Survival
- [ ] Oneblock
- [ ] Skyblock
- [ ] Minigames

### 📋 Description

When you do /sit, it shows Use **%Key%** to stand up!
Another minor bug!

### 📑 Reproduction Steps (Optional)

/sit
See the message
it says use %key% Key to Get Up!

### 💡 Expected Behavior

%Key% to be Sneak or Shift

### 📷 Screenshots / Videos

![unknown](https://user-images.githubusercontent.com/96323384/147382259-1a0257b5-a2bb-4da9-a85b-8e5c9bbb3a37.png)

### 🎮 Minecraft Version

1.18

### 🎮 Minecraft Client Mod

Optifine

### 🎮 Operating system 

Windows

### 💡 Extra Client Mods (Optional)

none

**Comment by DestinedPhoenix** [comment]
Credit to ibrahimslayer/Jr.Drek for first mentioning this bug on the server's discord channel - bugreports.
For the better explanation, I posted it here.

**Comment by SpikeyHelmet** [comment]
Fixed.

**Comment by DestinedPhoenix** [comment]
👍 Done, yeah.
