### ISSUE TITLE
[BUG] PVP bugged in OB

### ISSUE THREAD

**Issue by DestinedPhoenix** [MCIndiaNetwork/MCI-Server#32]
### ✅ Server

- [ ] Survival
- [X] Oneblock
- [ ] Skyblock
- [ ] Minigames

### 📋 Description

You cant pvp in pvp arena now.
check video
AND ALSO SORRY FOR SOME UNIMPORTANT PARTS IN THE VIDEO.
Credit: OP_JAY 2

### 📑 Reproduction Steps (Optional)

/warp pvp
try to fight someone
either cant hit each other

### 💡 Expected Behavior

To start fighting and eventually die or win.

### 📷 Screenshots / Videos

https://user-images.githubusercontent.com/96323384/147447670-7d162f3c-1998-4f47-a6d3-12b5adbfb968.mp4

### 🎮 Minecraft Version

1.18

### 🎮 Minecraft Client Mod

Vanilla

### 🎮 Operating system 

Windows

### 💡 Extra Client Mods (Optional)

none

**Comment by SpikeyHelmet** [comment]
Fixed
