### ISSUE TITLE
[BUG]Crafting Enchanted Golden Apples 

### ISSUE THREAD

**Issue by Undercover07** [MCIndiaNetwork/MCI-Server#33]
### ✅ Server

- [ ] Survival
- [X] Oneblock
- [ ] Skyblock
- [ ] Minigames

### 📋 Description

we can still craft enchanted golden apples though the crafting recipe had been removed long ago, they had been made rare due to it being too OP. 

### 📑 Reproduction Steps (Optional)

1. Place 8 gold blocks in a crafting table
2. Then place a apple in the center
3. You can easily craft the enchanted golden apple

### 💡 Expected Behavior

We shouldn't be able to craft Enchanted Golden Apples and by doing the steps above, we should not be able to craft Enchanted Golden Apples as people are using it just like any other normal food source..... 

### 🎮 Minecraft Version

1.18

### 🎮 Minecraft Client Mod

Optifine

### 🎮 Operating system 

Windows

**Comment by DestinedPhoenix** [comment]
It's maybe intentional. 1.8 style something maybe. ###I am not really sure about it though.

**Comment by smyaknti** [comment]
It is being looked into. Changes and additions would be made to balance it.

**Comment by SpikeyHelmet** [comment]
It's being removed tomorrow!
