### ISSUE TITLE
Vote site 404 error

### ISSUE THREAD

**Issue by DestinedPhoenix** [MCIndiaNetwork/MCI-Server#34]
### ✅ Server

- [ ] Survival
- [ ] Oneblock
- [ ] Skyblock
- [ ] Minigames

### 📋 Description

When you type mcindia vote on google or use the general vote link site featuring all sites has 404 error i. e. page not found. 
Add it there. 

### 📑 Reproduction Steps (Optional)

click on the link to main site. 
Try to see five links but dont find any. 
so no option except for /vote ingame but sometimes when we are not there ingame we need this. 

### 💡 Expected Behavior

See 5 links. 
Open each and vote. 

### 📷 Screenshots / Videos

![IMG_20220103_205903](https://user-images.githubusercontent.com/96323384/147949483-3ddb28e8-1511-44ab-b2a4-61c036fd9462.jpg)

### 🎮 Minecraft Version

1.18

### 🎮 Minecraft Client Mod

Optifine

### 🎮 Operating system 

Windows

### 💡 Extra Client Mods (Optional)

None

**Comment by Adityakhalkar** [comment]
yes MCI forums site is down for some revamp

**Comment by elli0t43** [comment]
Its online now!

**Comment by DestinedPhoenix** [comment]
Yes, done! Many were complaining about this and this was true, so I reported this. Didn't get time yesterday night, was about to close it, but now its closed. So, no problem.
