### ISSUE TITLE
[BUG] Blocks become invisible for few seconds at 1.18  Build height limit

### ISSUE THREAD

**Issue by hyprex-deva** [MCIndiaNetwork/MCI-Server#35]
### ✅ Server

- [X] Survival
- [ ] Oneblock
- [ ] Skyblock
- [ ] Minigames

### 📋 Description

The blocks sometimes becomes invisible when am standing at the Build Height limit (y=320).
And truly speaking, its kind of buggy at Build Height Limit. If I fire 3 to 4 arrows up, then I would see the arrows falling down 2 to 3 times(like seeing the arrows falling down again and again for sometime).

[Though I don't know if the reason for there occurrences is that, I joined from 1.17.1 version.]

### 📑 Reproduction Steps (Optional)

Just Roaming around Water Elevator at World Build Height Limit.

### 💡 Expected Behavior

The Blocks should not become Invisible.

### 📷 Screenshots / Videos

![2022-01-06_11 21 47](https://user-images.githubusercontent.com/96543076/148337745-41f4a161-1ca7-4538-8e4f-7d0a23036bd5.png)
![2022-01-06_11 21 47_2](https://user-images.githubusercontent.com/96543076/148337749-621a693c-53c7-475b-b69f-5c17031d9d15.png)
![2022-01-06_11 21 48](https://user-images.githubusercontent.com/96543076/148337753-b06eda67-4f44-4a37-96fa-e0bd73b74100.png)
![2022-01-06_11 21 48_4](https://user-images.githubusercontent.com/96543076/148337754-2bdd6ec8-3798-48e7-bc5a-333a4ee1f475.png)
![2022-01-06_11 21 49_5](https://user-images.githubusercontent.com/96543076/148337755-3777237b-be64-4af4-8ea7-9670b3cfcdb6.png)

### 🎮 Minecraft Version

1.17.x

### 🎮 Minecraft Client Mod

Optifine

### 🎮 Operating system 

Windows

**Comment by smyaknti** [comment]
You are on 1.17 and expecting 1.18 behavior. 1.17 can render blocks above build height but its through a hacky way. Please use the proper intended minecraft version.
