### ISSUE TITLE
[BUG]Basalt Generator GUI problem

### ISSUE THREAD

**Issue by RohanKohalli** [MCIndiaNetwork/MCI-Server#38]
### ✅ Server

- [ ] Survival
- [X] Oneblock
- [ ] Skyblock
- [ ] Minigames

### 📋 Description

In oneblock generator menu name of many ores are missing and when you hover on basalt generator half the details go out of screen

### 💡 Expected Behavior

Even after setting GUI scale to 2 basalt generator details are not visible. Few weeks ago we could read info about basalt generator perfectly

### 📷 Screenshots / Videos

![2022-01-22_20 03 39](https://user-images.githubusercontent.com/66159081/150643124-71a7c149-6840-4742-bda4-2dbdf38fe1e9.png)
![2022-01-22_20 03 36](https://user-images.githubusercontent.com/66159081/150643131-a286a871-d3dd-4446-aa1d-4250c57a9495.png)

### 🎮 Minecraft Version

1.18

### 🎮 Minecraft Client Mod

Optifine

### 🎮 Operating system 

Windows

**Comment by SpikeyHelmet** [comment]
Will check on this

**Comment by SpikeyHelmet** [comment]
Fixed.
