### ISSUE TITLE
 after breaking the ob block, it isnt spawning normally but spawns after you hit other block and goes again after breaking and i dont get the stuff

### ISSUE THREAD

**Issue by ineedhelpirlok** [MCIndiaNetwork/MCI-Server#39]
### ✅ Server

- [ ] Survival
- [X] Oneblock
- [ ] Skyblock
- [ ] Minigames

### 📋 Description

after breaking the ob block, it isnt spawning normally but spawns after you hit other block. it is not because of the ping because i have ethernet + 50 ms and i tried relogging but its not going and its been 2 days :)

### 📑 Reproduction Steps (Optional)

idk

### 💡 Expected Behavior

i thought its gonna go after relogging but it didnt im very sad

### 📷 Screenshots / Videos

![2022-02-03_10 53 05](https://user-images.githubusercontent.com/98936229/152286157-ce104cf8-5463-414c-8f7e-d133c9d7b578.png)

### 🎮 Minecraft Version

1.16.x

### 🎮 Minecraft Client Mod

Optifine

### 🎮 Operating system 

Windows

**Comment by smyaknti** [comment]
It can be a network packet loss or something. Plus you are in 1.16 and the server is in 1.17 so the block update method is differernt. I would suggest using 1.17 to solve this issue. Else follow up on this.

**Comment by SpikeyHelmet** [comment]
Closing, haven't heard anyone else complain about this

**Comment by DestinedPhoenix** [comment]
I don't know, try placing a block there when it happens. It used to happen with me during the ocean phase i used to place a random block there, and it would regenerate.
