### ISSUE TITLE
Cave spider bug 

### ISSUE THREAD

**Issue by ibrahimslayer** [MCIndiaNetwork/MCI-Server#45]
### ✅ Server

- [X] Survival
- [ ] Oneblock
- [ ] Skyblock
- [ ] Minigames
- [ ] Bedwars

### 📋 Description

cave spiders don't drop anything 
upon killing a cave spider, nothing is dropped
not even exp 

### 📑 Reproduction Steps (Optional)

1. find a cave spider
2. kill it

### 💡 Expected Behavior

string/spider eye and exp is expected to be dropped  

### 🎮 Minecraft Version

1.17.x

### 🎮 Minecraft Client Mod

Optifine

### 🎮 Operating system 

Windows

### 💡 Extra Client Mods (Optional)

optifine

**Comment by SpikeyHelmet** [comment]
Bug already fixed.
