### ISSUE TITLE
[BUG] stable blocks 

### ISSUE THREAD

**Issue by ibrahimslayer** [MCIndiaNetwork/MCI-Server#46]
### ✅ Server

- [X] Survival
- [ ] Oneblock
- [ ] Skyblock
- [ ] Minigames
- [ ] Bedwars

### 📋 Description

when you get combat logged with daxis, stable blocks dont drop 

### 📑 Reproduction Steps (Optional)

first get daxis and use them
second hit someone and log out while you're still in combat
then come bak to see if your stable blox dropped 

### 💡 Expected Behavior

i expect stable blocks to drop and be there unless someone picks them up 

### 🎮 Minecraft Version

1.17.x

### 🎮 Minecraft Client Mod

Optifine

### 🎮 Operating system 

Windows

### 💡 Extra Client Mods (Optional)

optifine

**Comment by SpikeyHelmet** [comment]
Issue has been fixed!
