### ISSUE TITLE
/msg in BEDWARS while a match is running

### ISSUE THREAD

**Issue by DestinedPhoenix** [MCIndiaNetwork/MCI-Server#47]
### ✅ Server

- [ ] Survival
- [ ] Oneblock
- [ ] Skyblock
- [ ] Minigames
- [X] Bedwars

### 📋 Description

This is actually like a defect, not exactly a bug.
When someone is spectating he/she can /msg a player in game.
this way a few players actually get an advantage and kind of cheat.
[Today, a player just messaged his friend due to which i died. Basically, a player also told me about this bug two days back when he actually showed me by messaging. This causes your strats to fail, he said he was hiding at mid and getting emeralds and a player at the far end of the map came to know about it, it might be his badluck but still this can be the case that a spectator messaged the other guy.]

### 📑 Reproduction Steps (Optional)

1. Die through a final kill.
2. Open chat.
3. /msg to a player something.
4. Message is delivered.

### 💡 Expected Behavior

An error message: "`Sorry you can't do this while a match is running!`"

### 📷 Screenshots / Videos

![2022-04-26_12 16 47](https://user-images.githubusercontent.com/96323384/165263487-c2405b01-7583-45d5-ae84-a0a3f59f77ee.png)

### 🎮 Minecraft Version

1.18

### 🎮 Minecraft Client Mod

Optifine

### 🎮 Operating system 

Windows

### 💡 Extra Client Mods (Optional)

None

**Comment by SpikeyHelmet** [comment]
Removed the command usage in Bedwars
