### ISSUE TITLE
Bug Report Format

### ISSUE THREAD

**Issue by elli0t43** [MCIndiaNetwork/MCI-Server#5]
# The format of Bug Report

| name | about | title | labels | assignees | 
|--|--|--|--|--|
| Bug report | Create a report to help us improve | title about the bug | "[BUG]", "[Type of Server]"|  | 

---

**Describe the bug :**

**Name of the Server(Oneblock/Survival/Minigames) :**
Name the server

**To Reproduce :**
Steps to reproduce the behavior in exact manner:

**Expected behavior :**

**Screenshots :**

**Client and Mods used (please complete the following information as much as you can) :**
 - OS: 
 - Minecraft Client:
 - All mods:
 - Game version

**Additional context :**

**Comment by SpikeyHelmet** [comment]
Thanks for the contribution!
