### ISSUE TITLE
Sentinel before playtime 

### ISSUE THREAD

**Issue by DestinedPhoenix** [MCIndiaNetwork/MCI-Server#53]
### ✅ Server

- [ ] Survival
- [X] Oneblock
- [ ] Skyblock
- [ ] Minigames
- [ ] Bedwars

### 📋 Description

(back after two months)
You can reach sentinel before having enough playtime by right clicking the book twice.

### 📑 Reproduction Steps (Optional)

1. Get book.
2. Right click twice.
3. You ranked up to Sentinel.

### 💡 Expected Behavior

Not enough playtime - message to be displayed in chat.

### 📷 Screenshots / Videos

![image](https://user-images.githubusercontent.com/96323384/180433281-99b42303-da2d-4187-84c1-4b69b9c0ce3f.png)

### 🎮 Minecraft Version

1.18

### 🎮 Minecraft Client Mod

Optifine

### 🎮 Operating system 

Windows

### 💡 Extra Client Mods (Optional)

none

**Comment by DestinedPhoenix** [comment]
Credit (for SS): CutiePieLiz
He/She did it because i told her. Don't take away the rank. 😉

**Comment by SpikeyHelmet** [comment]
Noted, bug will be solved
