### ISSUE TITLE
[BUG]Tp plugin is showing that teleportation cancelled, even if the player doesn't move

### ISSUE THREAD

**Issue by Adityakhalkar** [MCIndiaNetwork/MCI-Server#6]
**description**
When you run the command /tpa {name}, and when the person accepts tp, it says teleportation cancelled, even though the player didn't moved, and basically it happens only when the teleporter person moves within 3 secs

**Name of the Server(Oneblock/Survival/Minigames) :**
Oneblock

**To Reproduce :**
Steps to reproduce the behavior in exact manner:
1)type /tpa {name}
2)tell the person to accept
3)dont move, the Teleportation must be cancelled automatically
**Expected behavior :**
It should teleport the player

**Screenshots :**
none, i will try to get one though

**Client and Mods used (please complete the following information as much as you can) :**
 - OS: windows
 - Minecraft Client:tlauncher
 - All mods:none
 - Game version:1.17

**Additional context :**
None

**Comment by SpikeyHelmet** [comment]
Okay, will patch this out by tonight.

**Comment by Adityakhalkar** [comment]
I guess this issue too is fixed, so you can close this one too
