### ISSUE TITLE
[BUG] Slot 9 in Bedwars lobby is bugged

### ISSUE THREAD

**Issue by Agr1m** [MCIndiaNetwork/MCI-Server#60]
### ✅ Server

- [ ] Survival
- [ ] Oneblock
- [ ] Skyblock
- [ ] Minigames
- [X] Bedwars

### 📋 Description

We sometimes have player show/hide option in slot9, sometimes we have gadgets menu.

### 💡 Expected Behavior

I expect that there should be another slot for Show/hide players menu or Gadgets menu

### 📷 Screenshots / Videos

![image](https://user-images.githubusercontent.com/103027757/203818532-573ee65f-8ee3-4798-a9bb-78928dacfe66.png)
![image](https://user-images.githubusercontent.com/103027757/203818576-0a84681a-4c31-415a-97cd-47a0d1d920a4.png)

### 🎮 Minecraft Version

1.8.9

### 🎮 Minecraft Client Mod

Optifine

### 🎮 Operating system 

Windows

**Comment by Agr1m** [comment]
PS: after just logging in the bw lobby we always have show/hide players and after playing a game it shows us gadgets menu and show/hide players menu is gone.
![image](https://user-images.githubusercontent.com/103027757/203824755-4bf90e18-4f6d-46f7-a715-7047e7995579.png)

**Comment by SpikeyHelmet** [comment]
Changed the slot
