### ISSUE TITLE
oneblock sellgui 

### ISSUE THREAD

**Issue by RohanKohalli** [MCIndiaNetwork/MCI-Server#63]
### ✅ Server

- [ ] Survival
- [X] Oneblock
- [ ] Skyblock
- [ ] Minigames
- [ ] Bedwars

### 📋 Description

When u put an item in sellgui menu even thought the can be sold it gives error item not found

### 📑 Reproduction Steps (Optional)

In oneblock
1.type /sellgui
2. put any item which can be sold in shop
3. when u press back it returns in ur inventory and displays no items found

### 💡 Expected Behavior

once u put the item for sell it should give u equivalent money 

### 📷 Screenshots / Videos

![Screenshot from 2022-12-08 10-35-20](https://user-images.githubusercontent.com/66159081/206361402-718bf17d-5c44-45f2-8286-fbbe83a6a17a.png)
![Screenshot from 2022-12-08 10-35-30](https://user-images.githubusercontent.com/66159081/206361408-8208c2ed-e94c-4f0b-88dc-991aefa76937.png)

### 🎮 Minecraft Version

1.19.x

### 🎮 Minecraft Client Mod

Optifine

### 🎮 Operating system 

Linux

**Comment by SpikeyHelmet** [comment]
Noted. Oneblock will be moving to a newer economy system.

**Comment by SpikeyHelmet** [comment]
Resolved
