### ISSUE TITLE
[BUG]Ender chest bug

### ISSUE THREAD

**Issue by shramann** [MCIndiaNetwork/MCI-Server#7]
in ob,after we place enderchest in our island (ik we can do /ec) but after we place the chest ,it shows "ender chests are disabled" and then we cant break the enderchest

**Name of the Server(Oneblock/Survival/Minigames) :**
Oneblock

**Client and Mods used (please complete the following information as much as you can) :**
 - OS: w11
 - Minecraft Client:tl optifine 1.17.1
 - All mods:no mods
 - Game version:1.17.1
 @elli0t43

**Comment by elli0t43** [comment]
Did you checked your Oneblock settings from `/ob settings` ?

**Comment by shramann** [comment]
agreed..i posted before checking my settings sry my bad..but is it related to not able to break the ec? uhh
