### ISSUE TITLE
[BUG]Challenges that cannot be completed

### ISSUE THREAD

**Issue by Undercover07** [MCIndiaNetwork/MCI-Server#8]
**Describe the bug :**
Some challenges cannot be completed.

**Name of the Server(Oneblock/Survival/Minigames) :**
Name the server: OneBlock

**To Reproduce :**
Steps to reproduce the behavior in exact manner:

**Expected behavior :**

Remove the challenge or allow us to tame Donkeys

**Screenshots :**

**Client and Mods used (please complete the following information as much as you can) :**
 - OS: Windows
 - Minecraft Client: TLauncher
 - All mods:
 - Game version: 1.17.1

**Additional context :**
We cannot complete certain challenges like the one in which we need to have all the Potions in our inventory,we have all the potions mentioned, even then we cannot complete that challenge. Another one in which we need to have all the friendly mobs on our OB, it cannot be completed because we cannot tame Donkeys and so we cannot get mules which makes it impossible to complete that challenge.

**Comment by SpikeyHelmet** [comment]
1. You no longer need a donkey and mule to complete the taming challenge
2. removed the potion challenge

Will be adding more challenges that are even harder to obtain with exclusive items!
